version: '3.8'

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: computer_sphere
    volumes:
      - postgres-data:/var/lib/postgresql/data

  goose:
    image: golang:1.22.4-alpine
    container_name: goose
    depends_on:
      - postgres
    volumes:
      - ./database/migrations:/migrations
      - ./database:/go/src/app
    working_dir: /go/src/app
    entrypoint: >
      sh -c "
      apk add --no-cache git && 
      go get -u github.com/pressly/goose/v3/cmd/goose && 
      goose -dir /migrations postgres 'user=youruser password=yourpassword dbname=yourdb sslmode=disable' up
      "

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    depends_on:
      - goose
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: computer_sphere
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080
    volumes:
      - ./client:/app

volumes:
  postgres-data:
