// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Result struct {
	ID          int32
	TaskID      sql.NullInt32
	UserID      sql.NullInt32
	Output      pqtype.NullRawMessage
	ElapsedTime sql.NullInt64
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Task struct {
	ID         int32
	Name       string
	Payload    pqtype.NullRawMessage
	Parameters pqtype.NullRawMessage
	Status     string
	AssignedTo sql.NullInt32
	Priority   sql.NullInt32
	Retries    sql.NullInt32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
